#!/bin/sh

echo "This is experimental; it may not work." > /dev/console
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
rm /etc/mtab
mount /dev/sda2 /
mount /dev/sda1 /boot
swapon /dev/sda3
accton /etc/default/acct
rm -rf /usr/tmp/*
rm -rf /tmp/*
uname -a > /dev/console

if [ "$(cat /etc/hostname)" != "" ]
then
    hostname $(cat /etc/hostname)
else
    hostname localhost
fi

if [ -e /etc/rc.d ]
then
	sh /etc/rc.d/*.sh
fi
