#!/bin/sh

# Begin by sourcing /etc/profile, and mounting the filesystems
. /etc/profile
echo "V7 Init on $(uname -srm)" > /dev/console
mount -a
swapon -a

# Remount as read write
mount -o remount,rw /

# Start logging
echo "BEGIN: Started V7 Init on $(uname -srm)" > /var/log/v7init.log
echo "info:  Filesystems are now mounted" >> /var/log/v7init.log

# Set the hostname
if [ ! -e /etc/hostname ] || [ "$(cat /etc/hostname)" = "" ]; then
    hostname localhost
else
    hostname `cat /etc/hostname`
fi

# Load all sysctl settings
sysctl --system

# Load the keyboard layout.
loadkeys `cat /etc/v7init/kbd.conf`

# Launch the services
for scripts in `ls /etc/v7init/en`; do
    . /etc/v7init/en/$scripts
    echo "Starting ${NAME}..." > /dev/console
    echo "info:  Starting ${NAME}" >> /var/log/v7init.log
    start
    if [ $? != 0 ]; then
        echo "error: ${NAME} failed to start." >> /var/log/v7init.log
        echo "${NAME} failed to start!" > /dev/console
    else
        echo "info:  ${NAME} started successfully." > /dev/console
    fi
done
