#!/bin/sh

# This must be run as root
if [ $(id -u) != 0 ]; then
	echo 'This must be run as root!'
	exit 1
fi

# Try to unmount all filesystems
umount -rat nodevtmpfs,nodebugfs,notmpfs,noproc,nosysfs
swapoff -a

# Trigger the kernel to synchronize the filesystems
echo s > /proc/sysrq-trigger

# Remount all filesystems read-only
echo u > /proc/sysrq-trigger
mount -fo remount,ro /

# Shutdown the system
echo o > /proc/sysrq-trigger
