#!/bin/sh
#
# A script to enable and disable v7init services.
#

if [ $(id -u) != 0 ]; then
    echo "You must run this as root!"
    exit 1
fi

cd /etc/v7init

disable()
{
    if [ ! -e "en_srv/$1" ]; then
        if [ -e "srv/$1.sh" ]; then
            echo "The service $1 is not enabled."
            exit 0
        else
            echo "The service $1 does not exist."
            exit 1
        fi
    fi

    rm "en_srv/$1"
    chmod 0644 "srv/$1.sh"
    echo "The service $1 has been disabled."
    exit 0
}

enable()
{
    if [ -e "en_srv/$1" ]; then
        echo "The service $1 has already been enabled."
        exit 0
    elif [ ! -e "srv/$1.sh" ]; then
        echo "The service $1 does not exist."
        exit 1
    fi

    touch "en_srv/$1"
    chmod 0755 "srv/$1.sh"
    echo "The service $1 has been enabled."
    exit 0
}

usage()
{
    echo "Usage: v7srv [-deh] service ..."
    echo ""
    echo "  -d, --disable    disable a service"
    echo "  -e, --enable     enable a service"
    echo "  -h, --help       display this output"
    echo ""
    exit $1
}

if [ "$2" = "" ]; then
    usage 1
fi

case "$1" in
    -d)
        disable "$2" ;;
    --disable)
        disable "$2" ;;
    -e)
        enable "$2" ;;
    --enable)
        enable "$2" ;;
    --help)
        usage 0 ;;
    -h)
        usage 0 ;;
    *)
        usage 1 ;;
esac
